### PR TITLE
Update runtime to GNOME 41

### PR DESCRIPTION
**Pull request by hfiguiere**

### CODE REVIEW

**Comment by Altonss** [comment]
Thanks for this PR, indeed the current GNOME 40 runtime has reached end-of-life :)

**Comment by hfiguiere** [comment]
but now 42 is out.

**Comment by Altonss** [comment]
I just saw this https://github.com/flathub/de.haeckerfelix.Shortwave/pull/14 :(

**Comment by hfiguiere** [comment]
This is now with 42.

I still biuld libadwaita as the version in the runtime breaks.

**Comment by x80486** [comment]
bot merge :wink:

**Comment by Altonss** [comment]
See here why it may take some time to merge this: https://gitlab.gnome.org/World/Shortwave/-/issues/633

**Comment by hfiguiere** [comment]
it just say "it will break"

**Pull request closed without merging**
