### PR TITLE
Upgrade to 3.38 runtime

### PR DESCRIPTION
**Pull request by fedelibre**
Pretty easy patch :-)

Maybe useful for others who don't want to install the old 3.36 runtime.

### CODE REVIEW

**Comment by Iolaum** [comment]
Old runtime gives the following EOL warning:

```
Info: org.gnome.Platform//3.36 is end-of-life, with reason:
   The GNOME 3.36 runtime is no longer supported as of February 13, 2021. Please ask your application developer to migrate to a supported platform.
```

Also unfortunately trying to use the test build returns an error:

```
$ flatpak install --user https://dl.flathub.org/build-repo/40338/de.haeckerfelix.Shortwave.flatpakref
error: Can't load uri https://dl.flathub.org/build-repo/40338/de.haeckerfelix.Shortwave.flatpakref: Server returned status 404: Not Found
```

@haecker-felix  Any chance on accepting/merging the PR. [Build 41925](https://flathub.org/builds/#/builders/32/builds/41925) appears to have been successful. (Since I can't install it, can't test it unfortunately, however a rebuild might alleviate that.)

**Comment by x80486** [comment]
Is it possible to use instead the just-release GNOME `40` instead of `3.38`?

**Comment by Iolaum** [comment]
@fedelibre @x80486 @bdaase 
I 've created another PR #12  with the Gnome 40 runtime. You can test with (not sure for how much flathub will keep the test build up):

```
flatpak install --user https://dl.flathub.org/build-repo/41365/de.haeckerfelix.Shortwave.flatpakref
```

From my testing things work fine.

CC  (and thanks for the software) @haecker-felix

**Comment by x80486** [comment]
Works fine for me...I think you can close this pull request and just let the other one.

**Comment by bilelmoussaoui** [comment]
Handled by #12 instead

**Pull request closed without merging**
